name: app_environment
channels:
  - snowflake
dependencies:
  - ipywidgets=*
  - plotly=*
  - snowflake-ml-python=1.6.2
  - snowflake-snowpark-python=1.22.1
  - snowflake.core=0.9.0
  - streamlit-chat=*
